{
    "openapi": "3.0.0",
    "info": {
        "title": "Api Gerenciamento de vagas",
        "version": "1.0.0",
        "description": "Api criada para gerenciamento e cadastro de vagas de emprego, para fins de estudo."
    },
    "paths": {
        "/api/auth/register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Cadastro de usuários",
                "description": "Rota responsável por cadastrar usuários",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/types/RegisterBody"
                            },
                            "example": {
                                "name": "Lucas Bot",
                                "email": "lucas@bot.com",
                                "password": "1234",
                                "confPassword": "1234",
                                "type": "recruiter"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "message": "success"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "User already exists": {
                                        "value": {
                                            "status": 400,
                                            "message": "User already registered"
                                        }
                                    },
                                    "Passwords don't match": {
                                        "value": {
                                            "status": 400,
                                            "message": "Passwords don't match"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login de usuário",
                "description": "Rota responsável por efetuar o login do usuário, salvando um cookie httpOnly contendo o token de autenticação",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/types/LoginBody"
                            },
                            "example": {
                                "email": "lucas@bot.com",
                                "password": "1234"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "message": "success"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "Wrong password": {
                                        "value": {
                                            "status": 400,
                                            "message": "Wrong password!"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "User not found": {
                                        "value": {
                                            "status": 404,
                                            "message": "User Not found"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Logout de usuário",
                "description": "Rota responsável por efetuar o logout do usuário, eliminando o token salvo nos cookies",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "message": "success"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "types": {
                "RegisterBody": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        },
                        "confPassword": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "email",
                        "password",
                        "confPassword",
                        "type"
                    ]
                },
                "LoginBody": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        }                 
                    },
                    "required": [
                       "email",
                       "password"
                    ]
                }
            },
            "api-responses": {
                "success": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}